Documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/**'
Source:
- changed-files:
  - any-glob-to-any-file: 'src/DLLPickle/**'
Dependencies:
- changed-files:
  - any-glob-to-any-file: 'src/DLLPickle/Lib/**'
Tests:
- changed-files:
  - any-glob-to-any-file: 'src/Tests/**'
