# https://docs.readthedocs.io/en/stable/config-file/index.html

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  fail_on_warning: true

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt

# Build HTML only (faster, PDF/ePub often unused)
formats: []
