name: Release and Publish

on:
  #workflow_run:
  #  workflows:
  #    - "1 - Update Dependencies"
  #    - "Update Dependencies"
  #  types: [completed]
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: read
  issues: write

jobs:
  release:
    # Run when manually dispatched or when the 'Update Dependencies' workflow succeeds.
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: windows-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Determine version bump type
        id: bump_type
        shell: pwsh
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_VERSION_BUMP: ${{ inputs.version_bump }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if ($env:EVENT_NAME -eq "workflow_dispatch") {
            $bumpType = $env:INPUT_VERSION_BUMP
          } else {
            # For automated dependency updates, default to patch
            $bumpType = "patch"

            # Optional: infer from PR title when present
            $prTitle = $env:PR_TITLE
            if ($prTitle -match 'major|breaking') {
              $bumpType = "major"
            } elseif ($prTitle -match 'minor|feature') {
              $bumpType = "minor"
            }
          }

          Write-Host "Version bump type: $bumpType"
          "bump_type=$bumpType" >> $env:GITHUB_OUTPUT

      - name: Update module version
        id: update_version
        shell: pwsh
        run: |
          $ManifestPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "src/DLLPickle/DLLPickle.psd1"

          # Read current manifest
          $Manifest = Import-PowerShellDataFile -Path $ManifestPath
          $CurrentVersion = [version]$Manifest.ModuleVersion

          # Determine new version based on bump type
            $bumpType = "${{ steps.bump_type.outputs.bump_type }}"
          switch ($bumpType) {
              'major' {
                  $NewVersion = "{0}.0.0" -f ($CurrentVersion.Major + 1)
              }
              'minor' {
                  $NewVersion = "{0}.{1}.0" -f $CurrentVersion.Major, ($CurrentVersion.Minor + 1)
              }
              'patch' {
                  $NewVersion = "{0}.{1}.{2}" -f $CurrentVersion.Major, $CurrentVersion.Minor, ($CurrentVersion.Build + 1)
              }
              default {
                  Write-Error "Invalid bump type: $bumpType"
                  exit 1
              }
          }

          Write-Host "Updating version from $CurrentVersion to $NewVersion"

          # Update manifest
          Update-ModuleManifest -Path $ManifestPath -ModuleVersion $NewVersion

          "new_version=$NewVersion" >> $env:GITHUB_OUTPUT
          "old_version=$CurrentVersion" >> $env:GITHUB_OUTPUT

      - name: Validate manifest version update
        shell: pwsh
        run: |
          $ManifestPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "src/DLLPickle/DLLPickle.psd1"
          $Manifest = Import-PowerShellDataFile -Path $ManifestPath
          $Expected = "${{ steps.update_version.outputs.new_version }}"
          if ($Manifest.ModuleVersion -ne $Expected) {
            Write-Error "Manifest version validation failed. Expected $Expected, found $($Manifest.ModuleVersion)"
            exit 1
          }
          Write-Host "Manifest version validated: $Expected"

      - name: Extract change summary
        id: changes
        shell: pwsh
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          # Try to extract update summary from PR body or title
          if ($env:EVENT_NAME -eq "pull_request") {
            $prBody = @"
          $env:PR_BODY
          "@

              # Extract package updates from PR body
              if ($prBody -match 'following tracked packages[:\s]*([^\r\n]+)') {
                  $changeSummary = $matches[1].Trim()
              } else {
              $changeSummary = $env:PR_TITLE
              }
          } else {
            $changeSummary = ($env:EVENT_NAME -eq "workflow_run") ? "Automated dependencies release" : "Manual release triggered"
          }

          Write-Host "Change summary: $changeSummary"
          "summary=$changeSummary" >> $env:GITHUB_OUTPUT

      - name: Commit version update
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add src/DLLPickle/DLLPickle.psd1
          git commit -m "chore(release): bump version to ${{ steps.update_version.outputs.new_version }}"
          git push origin HEAD:main
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Git push failed; aborting release."
            exit 1
          }

      - name: Capture commit SHA
        id: commit_sha
        shell: pwsh
        run: |
          $sha = git rev-parse HEAD
          Write-Host "Commit SHA: $sha"
          "sha=$sha" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          tag_name: v${{ steps.update_version.outputs.new_version }}
          name: Release v${{ steps.update_version.outputs.new_version }}
          target_commitish: ${{ steps.commit_sha.outputs.sha }}
          body: |
            ## 🚀 Release v${{ steps.update_version.outputs.new_version }}

            ### Changes
            ${{ steps.changes.outputs.summary }}

            ### Version Information
            - **Previous Version**: ${{ steps.update_version.outputs.old_version }}
            - **New Version**: ${{ steps.update_version.outputs.new_version }}
            - **Bump Type**: ${{ steps.bump_type.outputs.bump_type }}

            ### Installation
            ```powershell
            Install-Module -Name DLLPickle -RequiredVersion ${{ steps.update_version.outputs.new_version }}
            ```

            ---
            *This release was automatically created by the release workflow.*
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PowerShell Gallery
        id: publish_gallery
        shell: pwsh
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          $ModulePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "src/DLLPickle"

          try {
              Write-Host "Publishing module to PowerShell Gallery..."
              Publish-Module -Path $ModulePath -NuGetApiKey $env:PSGALLERY_API_KEY -Verbose -ErrorAction Stop
              Write-Host "✓ Module published successfully!"
          } catch {
              Write-Error "Failed to publish module: $_"
              exit 1
          }

      - name: Roll back manifest on publish failure
        if: steps.publish_gallery.conclusion == 'failure'
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          $ManifestPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "src/DLLPickle/DLLPickle.psd1"
          $OldVersion = "${{ steps.update_version.outputs.old_version }}"
          Write-Host "Rolling back manifest to $OldVersion due to publish failure"
          Update-ModuleManifest -Path $ManifestPath -ModuleVersion $OldVersion
          git add $ManifestPath
          git commit -m "chore(release): rollback manifest to $OldVersion due to PowerShell Gallery publish failure"
          git push origin HEAD:main

      - name: Annotate release on publish failure
        if: steps.publish_gallery.conclusion == 'failure'
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tagName = "v${{ steps.update_version.outputs.new_version }}"
          $annotation = @"

          ---

          ## ⚠️ PowerShell Gallery Publish Failed

          **Status**: This release was created but publishing to PowerShell Gallery failed.

          **Action Required**: The module manifest has been rolled back to version ${{ steps.update_version.outputs.old_version }}.

          **Next Steps**:
          1. Review the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for error details
          2. Fix the underlying issue
          3. Re-run the release workflow manually

          A tracking issue has been created automatically with failure details.
          "@

          try {
            gh release edit $tagName --notes-file - <<< $annotation
            Write-Host "✓ Release annotated with failure notice"
          } catch {
            Write-Warning "Failed to annotate release: $_"
          }

      - name: Create tracking issue on publish failure
        if: steps.publish_gallery.conclusion == 'failure'
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $issueTitle = "PowerShell Gallery publish failed for v${{ steps.update_version.outputs.new_version }}"
          $issueBody = @"
          ## 🚨 Release Publish Failure

          **Version**: v${{ steps.update_version.outputs.new_version }}
          **Workflow Run**: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          **Commit**: ${{ steps.commit_sha.outputs.sha }}
          **Release**: [v${{ steps.update_version.outputs.new_version }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ steps.update_version.outputs.new_version }})

          ### What Happened
          The release workflow successfully created a GitHub release for v${{ steps.update_version.outputs.new_version }}, but publishing to PowerShell Gallery failed.

          ### Automated Recovery Actions Taken
          - ✅ GitHub release created (remains available)
          - ✅ Module manifest rolled back to v${{ steps.update_version.outputs.old_version }}
          - ✅ Rollback commit pushed to main
          - ✅ Release annotated with failure notice

          ### Next Steps
          1. Review the workflow logs for the specific error message
          2. Common causes:
             - API key issues (check `PSGALLERY_API_KEY` secret)
             - Network connectivity problems
             - Gallery service outage
             - Module validation failures
          3. Once resolved, manually trigger the release workflow again

          ### To Retry
          ```bash
          gh workflow run "2 - Release.yml" --field version_bump=patch
          ```

          Or use the [Actions UI](${{ github.server_url }}/${{ github.repository }}/actions/workflows/2%20-%20Release.yml) to manually trigger.

          ---
          *This issue was automatically created by the release workflow.*
          "@

          try {
            gh issue create --title "$issueTitle" --body "$issueBody" --label "release,bug,automated"
            Write-Host "✓ Tracking issue created"
          } catch {
            Write-Warning "Failed to create tracking issue: $_"
          }

      - name: Summary
        if: always()
        shell: pwsh
        run: |
          $summary = @"
          ## Release Summary

          **Version**: ${{ steps.update_version.outputs.new_version }} (from ${{ steps.update_version.outputs.old_version }})

          **Bump Type**: ${{ steps.bump_type.outputs.bump_type }}

          **Changes**: ${{ steps.changes.outputs.summary }}

          **Status**: ${{ job.status }}

          ### Actions Taken
          - ✅ Module version updated
          - ✅ GitHub release created
          - $(if ('${{ steps.publish_gallery.conclusion }}' -eq 'failure') { '❌ PowerShell Gallery publish failed (rollback applied)' } else { '✅ Published to PowerShell Gallery' })

          Run ID: $env:GITHUB_RUN_ID
          "@

          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $summary
