<#
.SYNOPSIS
    Generates support and upstream-compatibility documentation from policy data.

.DESCRIPTION
    Produces the human-readable Microsoft support matrix and the profile-aware
    upstream evidence register. Pending CI or credential-dependent evidence is
    rendered as a gap and is never represented as passing.

.PARAMETER Check
    Compare generated content with committed files and throw on drift without writing.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$SupportPolicyPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'src/DLLPickle/SupportedRuntimeProfiles.json'),

    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$TestMatrixPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'build/powershell-test-matrix.json'),

    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$DependencyPolicyPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'build/dependency-policy.json'),

    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'docs/generated'),

    [Parameter()]
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'DLLPickle.ProfileEvidence.ps1')

foreach ($RequiredPath in @($SupportPolicyPath, $TestMatrixPath, $DependencyPolicyPath)) {
    if (-not (Test-Path -LiteralPath $RequiredPath -PathType Leaf)) {
        throw "Required documentation source was not found: $RequiredPath"
    }
}

$SupportPolicy = Get-Content -LiteralPath $SupportPolicyPath -Raw | ConvertFrom-Json -ErrorAction Stop
$TestMatrix = Get-Content -LiteralPath $TestMatrixPath -Raw | ConvertFrom-Json -ErrorAction Stop
$DependencyPolicy = Get-Content -LiteralPath $DependencyPolicyPath -Raw | ConvertFrom-Json -ErrorAction Stop
$DependencyPolicyDirectory = Split-Path -Path (Resolve-Path -LiteralPath $DependencyPolicyPath).Path -Parent

$ShippedProfileKeys = @($SupportPolicy.profiles | ForEach-Object { '{0}.{1}|{2}|{3}' -f $_.powerShellMajor, $_.powerShellMinor, $_.dotnetMajor, $_.targetFramework })
$TestProfileKeys = @($TestMatrix.profiles | ForEach-Object { '{0}.{1}|{2}|{3}' -f $_.powerShellMajor, $_.powerShellMinor, $_.dotnetMajor, $_.targetFramework })
if (Compare-Object -ReferenceObject $ShippedProfileKeys -DifferenceObject $TestProfileKeys) {
    throw 'Shipped runtime profiles and documentation test profiles do not align.'
}
$VerifiedDate = (ConvertTo-DLLPickleUtcDateTimeOffset -Value $TestMatrix.lastVerifiedUtc).ToString('yyyy-MM-dd')
$NewLine = "`r`n"

$SupportLines = [System.Collections.Generic.List[string]]::new()
$SupportLines.Add('# Supported PowerShell runtime matrix')
$SupportLines.Add('')
$SupportLines.Add('<!-- Generated by tools/New-DLLPickleSupportDocumentation.ps1. Do not edit by hand. -->')
$SupportLines.Add('')
$SupportLines.Add("Lifecycle and servicing data last verified: **$VerifiedDate**.")
$SupportLines.Add('')
$SupportLines.Add('| PowerShell line | Exact CI patch | .NET runtime | Bundled TFM | Microsoft lifecycle | Support end | Required OS cells |')
$SupportLines.Add('|---|---:|---:|---:|---|---:|---|')
foreach ($MatrixProfile in @($TestMatrix.profiles)) {
    $PowerShellLine = '{0}.{1}' -f $MatrixProfile.powerShellMajor, $MatrixProfile.powerShellMinor
    $SupportRow = '| {0} | {1} | {2} | `{3}` | {4} | {5} | Windows, Linux, macOS |' -f $PowerShellLine, $MatrixProfile.powerShellVersion, $MatrixProfile.dotnetRuntimeVersion, $MatrixProfile.targetFramework, $MatrixProfile.lifecycleState, $MatrixProfile.lifecycleEndDate
    $SupportLines.Add($SupportRow)
}
$SupportLines.Add('')
$SupportLines.Add('This table is the Microsoft-supported runtime contract used by the loader and CI. Upstream module compatibility is a separate evidence question; see [Upstream compatibility evidence](Compatibility-Evidence.md). Exact servicing patches are test pins, not minimum patch claims for end users.')
$SupportLines.Add('')
$SupportLines.Add('The module selects a bundle using both the PowerShell minor line and CLR major, then fails closed on a mismatched or unknown pair. Only the rows above are part of the current support contract.')
$SupportLines.Add('')
$SupportLines.Add('`multi-pwsh` is optional, checksum-pinned CI provisioning infrastructure. CI invokes the provisioned official `pwsh` executable directly. No multi-pwsh executable, package, manifest dependency, runtime reference, or license payload is published with DLLPickle.')

$EvidenceLines = [System.Collections.Generic.List[string]]::new()
$EvidenceLines.Add('# Upstream compatibility evidence')
$EvidenceLines.Add('')
$EvidenceLines.Add('<!-- Generated by tools/New-DLLPickleSupportDocumentation.ps1. Do not edit by hand. -->')
$EvidenceLines.Add('')
$EvidenceLines.Add('Microsoft runtime support and upstream module behavior are tracked independently. The rows below deliberately remain release-gating gaps until a profile-specific CI run is accepted; a supported PowerShell line does not imply that every upstream module combination can coexist in one process.')
$EvidenceLines.Add('')
$EvidenceLines.Add('| Module | Version | PowerShell | TFM | OS | Selected asset | Assembly / ALC result | Verdict | Evidence date | Run ID |')
$EvidenceLines.Add('|---|---|---:|---:|---|---|---|---|---:|---|')
foreach ($RuntimeProfile in @($DependencyPolicy.runtimeProfiles)) {
    foreach ($Platform in @($RuntimeProfile.platforms)) {
        $PlatformBaseline = $RuntimeProfile.baselines.$Platform
        $Verdict = if ($PlatformBaseline) { [string]$PlatformBaseline.status } else { 'missing-baseline' }
        $Evidence = $null
        $EvidenceDate = $VerifiedDate
        $RunReference = 'not-run'
        if ($Verdict -eq 'accepted') {
            if ([string]::IsNullOrWhiteSpace([string]$PlatformBaseline.evidencePath) -or
                [string]::IsNullOrWhiteSpace([string]$PlatformBaseline.evidenceFingerprint)) {
                throw "Accepted $Platform evidence for PowerShell $($RuntimeProfile.powerShellLine) has no committed path or fingerprint."
            }
            $EvidencePath = Join-Path -Path $DependencyPolicyDirectory -ChildPath ([string]$PlatformBaseline.evidencePath)
            if (-not (Test-Path -LiteralPath $EvidencePath -PathType Leaf)) {
                throw "Accepted profile evidence was not found: $EvidencePath"
            }
            $Evidence = Get-Content -LiteralPath $EvidencePath -Raw | ConvertFrom-Json -ErrorAction Stop
            $RecomputedEvidenceFingerprint = Get-DLLPickleNormalizedEvidenceFingerprint -Evidence $Evidence
            if ([string]$Evidence.contentFingerprint -ne $RecomputedEvidenceFingerprint -or
                [string]$PlatformBaseline.evidenceFingerprint -ne $RecomputedEvidenceFingerprint) {
                throw "Accepted profile evidence does not recompute to the policy fingerprint: $EvidencePath"
            }
            $PlatformLanes = @($TestMatrix.lanes | Where-Object platform -EQ $Platform)
            if ($PlatformLanes.Count -ne 1 -or [string]::IsNullOrWhiteSpace([string]$PlatformLanes[0].architecture)) {
                throw "The test matrix must declare exactly one architecture-bearing lane for '$Platform'."
            }
            $ExpectedProfileKey = 'ps{0}-{1}-{2}-{3}' -f $RuntimeProfile.powerShellLine, $RuntimeProfile.targetFramework, $Platform, $PlatformLanes[0].architecture
            if ([string]$Evidence.content.profile.profileKey -ne $ExpectedProfileKey) {
                throw "Accepted profile evidence '$($Evidence.content.profile.profileKey)' does not match '$ExpectedProfileKey'."
            }
            $EvidenceDate = (ConvertTo-DLLPickleUtcDateTimeOffset -Value $Evidence.provenance.capturedAtUtc).ToString('yyyy-MM-dd')
            $SourceRunId = [string]$Evidence.provenance.sourceRunId
            $SourceRunUrl = [string]$Evidence.provenance.sourceRunUrl
            $RunReference = if (-not [string]::IsNullOrWhiteSpace($SourceRunId) -and -not [string]::IsNullOrWhiteSpace($SourceRunUrl)) {
                '[{0}]({1})' -f $SourceRunId, $SourceRunUrl
            } elseif (-not [string]::IsNullOrWhiteSpace($SourceRunId)) {
                $SourceRunId
            } else {
                'committed evidence'
            }
        }
        foreach ($Module in @($DependencyPolicy.monitoredModules)) {
            if ($Evidence) {
                $EvidenceModules = @($Evidence.content.modules | Where-Object name -eq $Module.name)
                if ($EvidenceModules.Count -ne 1) {
                    throw "Accepted profile evidence for '$($Evidence.content.profile.profileKey)' does not contain exactly one '$($Module.name)' module row."
                }
                $EvidenceModule = $EvidenceModules[0]
                $SelectedAssetText = if (@($EvidenceModule.selectedAssets).Count -eq 0) {
                    'no tracked assembly selected'
                } else {
                    @($EvidenceModule.selectedAssets | ForEach-Object { '`{0}`' -f $_.selectedAsset }) -join '<br>'
                }
                $AssemblyResultText = if (@($EvidenceModule.selectedAssets).Count -eq 0) {
                    'no tracked assembly observed'
                } else {
                    @(
                        $EvidenceModule.selectedAssets |
                            ForEach-Object { '`{0}` {1} / `{2}`' -f $_.assemblyName, $_.assemblyVersion, $_.assemblyLoadContext }
                    ) -join '<br>'
                }
                $EvidenceRow = '| {0} | {1} | {2} | `{3}` | {4} | {5} | {6} | **{7}** | {8} | {9} |' -f $Module.name, $EvidenceModule.version, $RuntimeProfile.powerShellLine, $RuntimeProfile.targetFramework, $Platform, $SelectedAssetText, $AssemblyResultText, $Verdict, $EvidenceDate, $RunReference
            } else {
                $EvidenceRow = '| {0} | pending exact-profile inventory | {1} | `{2}` | {3} | pending CI artifact | pending hash and ALC | **{4}** | {5} | not-run |' -f $Module.name, $RuntimeProfile.powerShellLine, $RuntimeProfile.targetFramework, $Platform, $Verdict, $VerifiedDate
            }
            $EvidenceLines.Add($EvidenceRow)
        }
    }
}
$EvidenceLines.Add('')
$EvidenceLines.Add('## Known process-isolation requirement')
$EvidenceLines.Add('')
$EvidenceLines.Add('Issue #174 remains an expected limitation: ExchangeOnlineManagement and Az.Storage can require incompatible Microsoft.OData major versions. Both import orders are tested, but separate PowerShell processes remain the documented safe boundary until fresh evidence supports a narrower rule.')
$EvidenceLines.Add('')
$EvidenceLines.Add('## Preserved regression coverage')
$EvidenceLines.Add('')
$EvidenceLines.Add('- Issue #34: a deterministic negative-control/protected scenario verifies that Microsoft Graph authentication can bind `BaseAbstractApplicationBuilder.WithLogging(IIdentityLogger, Boolean)` after DLLPickle preloading.')
$EvidenceLines.Add('- Issue #193: package and runtime checks keep incidental `Microsoft.Extensions.*` assemblies out of the preload bundle.')
$EvidenceLines.Add('- PR #215: package, runtime, and ALC checks keep `Azure.Core` and `System.ClientModel` out of DLLPickle so Az.Accounts retains ownership of its private Azure SDK load context.')
$EvidenceLines.Add('- Issue #242: a worker-thread assembly-load scenario verifies that DLLPickle does not install PowerShell script-block assembly callbacks that can crash the process.')
$EvidenceLines.Add('')
$EvidenceLines.Add('## Authenticated read-only release gates')
$EvidenceLines.Add('')
$EvidenceLines.Add('The deterministic no-auth tier runs in CI. The following credential-dependent commands are not executed without approved credentials and must not be represented as passing:')
$EvidenceLines.Add('')
foreach ($Module in @($DependencyPolicy.monitoredModules)) {
    $GapRow = '- `{0}`: `{1}`' -f $Module.name, $Module.authenticatedReadOnlyProbeCommand
    $EvidenceLines.Add($GapRow)
}
$EvidenceLines.Add('')
$EvidenceLines.Add('These probes permit reads only; writes are not part of the validation tier. PowerShellEditorServices / VS Code coverage for issue #169 also remains an explicit manual gap unless a run artifact records it.')
$EvidenceLines.Add('')
$EvidenceLines.Add('Before the protected credentialed workflow exists, the release gate may accept one explicitly reviewed manual transition record for version `3.0.0`. That record must match the exact bundle-source fingerprint, cover the three exact Windows profiles and fixed read-only scenarios, contain no credential material or raw service output, record zero writes, and expire exactly 14 days after capture starts. It is transitional compatibility evidence, not least-privilege workload-identity proof.')

$Documents = [ordered]@{
    'Support-Matrix.md' = ($SupportLines -join $NewLine) + $NewLine
    'Compatibility-Evidence.md' = ($EvidenceLines -join $NewLine) + $NewLine
}

if ($Check.IsPresent) {
    $Drift = [System.Collections.Generic.List[string]]::new()
    foreach ($Document in $Documents.GetEnumerator()) {
        $Path = Join-Path $OutputDirectory $Document.Key
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
            $Drift.Add("Missing generated document: $Path")
            continue
        }
        $Actual = Get-Content -LiteralPath $Path -Raw
        if ($Actual -ne $Document.Value) {
            $Drift.Add("Generated document is stale: $Path")
        }
    }
    if ($Drift.Count -gt 0) {
        throw ($Drift -join ' ')
    }
} else {
    if (-not (Test-Path -LiteralPath $OutputDirectory -PathType Container)) {
        $null = New-Item -Path $OutputDirectory -ItemType Directory -Force
    }
    foreach ($Document in $Documents.GetEnumerator()) {
        Set-Content -LiteralPath (Join-Path $OutputDirectory $Document.Key) -Value $Document.Value -Encoding UTF8 -NoNewline
    }
}

[PSCustomObject]@{
    Checked   = $Check.IsPresent
    Documents = @($Documents.Keys | ForEach-Object { Join-Path $OutputDirectory $_ })
}
