name: Validate .NET Packages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/DLLPickle.Build/**'
      - 'src/DLLPickle.Build/packages.lock.json'
      - '.github/workflows/Validate-Packages.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/DLLPickle.Build/**'
      - 'src/DLLPickle.Build/packages.lock.json'
      - '.github/workflows/Validate-Packages.yml'

concurrency:
  group: ci-build-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    name: Build .NET Packages
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: 'src/DLLPickle.Build/packages.lock.json'

      - name: Restore dependencies
        shell: pwsh
        run: dotnet restore src/DLLPickle.Build/DLLPickle.csproj --locked-mode

      - name: Build
        shell: pwsh
        run: dotnet build src/DLLPickle.Build/DLLPickle.csproj --configuration Release --no-restore
